In [25]:
import pandas as pd
import numpy as np

In [26]:
car = pd.read_csv('Cleaned_Car.csv')

In [27]:
car.drop('Unnamed: 0',axis=1,inplace=True)

In [28]:
car.head()

name   company  year   Price  kms_driven fuel_type
0     Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1     Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
2       Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
3  Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
4               Ford Figo      Ford  2012  175000       41000    Diesel

In [29]:
X = car.drop(columns = 'Price')
y = car['Price']

In [30]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test  = train_test_split(X,y,test_size=0.2)

In [31]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.preprocessing import OneHotEncoder 
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline

In [32]:
ohe = OneHotEncoder()
ohe.fit(X[['name','company','fuel_type']])

OneHotEncoder()

In [33]:
column_trans = make_column_transformer((OneHotEncoder(categories=ohe.categories_),['name','company','fuel_type']),remainder='passthrough')

In [34]:
lr = LinearRegression()

In [35]:
pipe = make_pipeline(column_trans,lr)

In [36]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['Audi A3 Cabriolet', 'Audi A4 1.8', 'Audi A4 2.0', 'Audi A6 2.0',
       'Audi A8', 'Audi Q3 2.0', 'Audi Q5 2.0', 'Audi Q7', 'BMW 3 Series',
       'BMW 5 Series', 'BMW 7 Series', 'BMW X1', 'BMW X1 sDrive20d',
       'BMW X1 xDrive20d', 'Chevrolet Beat', 'Chevrolet Beat...
                                                                            array(['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Fiat', 'Force', 'Ford',
       'Hindustan', 'Honda', 'Hyundai', 'Jaguar', 'Jeep', 'Land',
       'Mahindra', 'Maruti', 'Mercedes', 'Mini', 'Mitsubishi', 'Nissan',
       'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'],
      dtype=object),
                                                                            array(['Diesel', 'LPG', 'Pe

In [37]:
y_pred = pipe.predict(X_test)

In [38]:
r2_score(y_test,y_pred)

0.7093434992697701

In [39]:
scores=[]
for i in range(1000):
    X_train,X_test,y_train,y_test  = train_test_split(X,y,test_size=0.2,random_state=i)
    lr=LinearRegression()
    pipe = make_pipeline(column_trans,lr)
    pipe.fit(X_train,y_train)
    y_pred = pipe.predict(X_test)
    scores.append(r2_score(y_test,y_pred))
    

In [40]:
np.argmax(scores)

433

In [41]:
scores[np.argmax(scores)]

0.8457042416667213

In [42]:
X_train,X_test,y_train,y_test  = train_test_split(X,y,test_size=0.2,random_state=np.argmax(scores))
lr=LinearRegression()
pipe = make_pipeline(column_trans,lr)
pipe.fit(X_train,y_train)
y_pred = pipe.predict(X_test)
r2_score(y_test,y_pred)

0.8457042416667213

In [43]:
import pickle

pickle.dump(pipe,open('LinearRegressionModel.pkl','wb'))

In [45]:
pipe.predict(pd.DataFrame([['Hyundai Santro Xing','Hyundai',2007,45000,'Petrol']],columns=['name','company','year','kms_driven','fuel_type']))

array([64199.89453682])

In [49]:
pipe.predict(pd.DataFrame([['Ford EcoSport Titanium','Ford',2014,36000,'Diesel']],columns=['name','company','year','kms_driven','fuel_type']))

array([489892.54602734])

In [50]:
pipe.predict(pd.DataFrame([['Hyundai Grand i10','Hyundai',2014,28000,'Petrol']],columns=['name','company','year','kms_driven','fuel_type']))

array([266813.58704334])